"""rename nota to nivel_foco

Revision ID: f4eb9d3495b0
Revises: 5fc3633af519
Create Date: 2026-05-11 15:14:56.952573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4eb9d3495b0'
down_revision: Union[str, Sequence[str], None] = '5fc3633af519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('nivel_foco', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'nota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('nota', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'nivel_foco')
    # ### end Alembic commands ###
